version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - etl_net

  spark-master:
    build:
      context: ./spark
      dockerfile: Dockerfile
    image: etl-spark:latest
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host 0.0.0.0
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - spark_data:/opt/spark_data
    networks:
      - etl_net

  dbadmin:
    image: adminer:latest
    container_name: dbadmin
    restart: always
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha
    networks:
      - etl_net
    depends_on:
      postgres:
        condition: service_healthy
  
  airflow:
    # image: apache/airflow:3.1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    depends_on:
      postgres:
        condition: service_healthy
      spark-master:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__FERNET_KEY: '46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho='
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.default
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__WEBSERVER__AUTHENTICATE: 'false'
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
      PYTHONPATH: /opt/spark_manager
      # AIRFLOW__LOGGING__LOGGING_LEVEL: DEBUG
      # AIRFLOW__AUTH__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
      - ./spark/spark_manager.py:/opt/spark_manager/spark_manager.py
      - spark_data:/opt/spark_data
    ports:
      - "8090:8080"
    networks:
      - etl_net
    user: "0:0"
    command: >
      bash -c "
      chmod 777 /opt/spark_data;

      echo 'Waiting for PostgreSQL...';
      while ! pg_isready -h postgres -p 5432 -U airflow -d airflow_db; do
        sleep 2;
      done;

      echo 'Migrating DB...';
      airflow db migrate;

      echo 'Starting Airflow...';
      airflow dag-processor &
      airflow scheduler &
      exec airflow api-server
      "

volumes:
  postgres_data:
  spark_data:

networks:
  etl_net:
    name: etl_net
    driver: bridge